@startuml WBS

' left to right direction

start
fork
:銀行でお金をおろす\n作業時間10分;
:スーパーで卵を買う\n作業時間10分;
:卵を洗う\n作業時間10分;
fork again
:お湯を沸かす\n作業時間20分;
' :卵をゆでる;
' :殻を割る;
' :塩を振る;
' fork again
' :腹筋して腹を減らす;
end fork
:卵をゆでる\n作業時間10分;
:殻を割る\n作業時間10分;
:塩を振る\n作業時間10分;
stop

:腹筋して腹を減らす\n作業時間30分;

@enduml